### ISSUE TITLE
:Shoulder, setting

### ISSUE THREAD

**Issue by qqmyers** [GlobalDataverseCommunityConsortium/dataverse-ansible#15]
When using the 
  doi
    shoulder: 
setting in main.yml, I'm seeing a :Shoulder setting with the correct value (the one I set) as well as a :Shoulder, setting (with an appended comma) that is set to '/'. The setting with the comma doesn't do anything, but I assume it is supposed to provide a default of '/' for :Shoulder?

**Comment by donsizemore** [comment]
whoops!

https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/master/tasks/dataverse-postinstall.yml#L106

will fix. thanks.

**Comment by donsizemore** [comment]
fixed.
