### ISSUE TITLE
Add release tags to enable inclusion of specific versions of this role

### ISSUE THREAD

**Issue by janvanmansum** [GlobalDataverseCommunityConsortium/dataverse-ansible#16]
We include `dataverse-ansible` as an external role in our Ansible project, using `ansible-galaxy` and a `requirements.yml` (see https://galaxy.ansible.com/docs/using/installing.html#installing-multiple-roles-from-a-file). Currently we can only refer to the latest commit of `datavers-ansible`. Please, consider creating release tags, so that it becomes possible to reference a specific version.

**Comment by donsizemore** [comment]
@janvanmansum In hindsight I should've done so at 4.20 / Glassfish4 (sorry)

Will tag for Payara 5 / Dataverse 5.0 stable, which is right around the corner.

**Comment by janvanmansum** [comment]
That'd be great. Thanks!
