### ISSUE TITLE
Use of Ansible "script" module leads to executable format error when run from Mac

### ISSUE THREAD

**Issue by janvanmansum** [GlobalDataverseCommunityConsortium/dataverse-ansible#18]
Currently, the only way I can run dataverse-ansible from my MacBook to configure a Linux VM is to use an ansible_local connection. If I understand it correctly, this means that ansible is then installed and run on the Linux VM. The reason for this seems to be the use of the Ansible "script" module which compiles and runs the script that it is passed into an executable. However, this executable is apparently created on my MacBook and therefore in a binary format that cannot be run on Linux, resulting in an error. Having to use ansible_local (or run Ansible from a compatible Linux machine, I guess) seems an unfortunate restriction to me. Would it be feasible to replace the calls to "script" with calls to "shell"?

* https://docs.ansible.com/ansible/latest/modules/script_module.html
* https://docs.ansible.com/ansible/latest/modules/shell_module.html
* https://docs.ansible.com/ansible/latest/plugins/connection/local.html

**Comment by donsizemore** [comment]
perfectly reasonable. I had used the "script" module due to Ansible's crabbing about it =)
