### ISSUE TITLE
upgrade to Solr 8.11.1

### ISSUE THREAD

**Issue by donsizemore** [GlobalDataverseCommunityConsortium/dataverse-ansible#198]
to deal with Log4Everything

**Comment by donsizemore** [comment]
Current state of Solr-8.11.1 and integration tests using our existing schema.xml and solrconfig.xml:

`solrconfig.xml: <jmx> is no longer supported, use solr.xml:/metrics/reporter section instead`

```
[ERROR]   SearchIT.testSearchCitation:182 » IllegalArgument Cannot get property 'items' ...", 
[ERROR]   SearchIT.testSearchPermisions:76 » IllegalArgument Cannot get property 'total_..."
```

**Comment by qqmyers** [comment]
See [#8325](https://github.com/IQSS/dataverse/issues/8325) for another 8.11.1 issue

**Comment by poikilotherm** [comment]
See also iqss/dataverse#7662 and iqss/dataverse#8320

**Comment by qqmyers** [comment]
FWIW: With the recent merges, the commit above (at least the main.yml changes) are needed to run ansible on the dev branch.

**Comment by donsizemore** [comment]
Yeah, I had pushed this change to Jenkins.yml but not the others (which default to the 5.9 release, which won't like 8.11.1(?)). Suggestions on the cleanest way to communicate this temporary condition welcome?

**Comment by donsizemore** [comment]
Solr got bumped to 8.11.1 for everyone with the 5.10 release, closing.
