### ISSUE TITLE
Jenkins failing with `ModuleNotFoundError: No module named 'selinux'`

### ISSUE THREAD

**Issue by pdurbin** [GlobalDataverseCommunityConsortium/dataverse-ansible#238]
Recent PRs such as these...

- https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-8758/1/console
- https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-8761/1/console

... seem to be failing with 

`TASK [dataverse : set httpd_can_network_connect on and keep it persistent across reboots] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'selinux'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (libselinux-python) on ip-172-31-16-42.ec2.internal's Python /usr/bin/python3.8. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}`

@donsizemore sez "it's picking up Ansible-5.4 from Rocky's 8.6 updates (even though the Rocky 8.6 AMI isn't yet available, which is why I haven't tested said). I've been keeping an eye on https://rockylinux.org/cloud-images/ but no 8.6 image just yet."

**Comment by donsizemore** [comment]
@pdurbin https://bugzilla.redhat.com/show_bug.cgi?id=1932650 sez `Now that ansible-core in RHEL 8.6 depends on python38 and sets it as the default python binary, I think this bug should be reopened and a solution reconsidered`
