### ISSUE TITLE
Installation of DescTools silently fails on Debian

### ISSUE THREAD

**Issue by HenningTimm** [GlobalDataverseCommunityConsortium/dataverse-ansible#251]
The [task installing r modules](https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/develop/tasks/rserve.yml#L80) fails silently, when a module cannot be installed. In my case `DescTools` requires two additional packages (`libcurl4-openssl-dev` and `libssl-dev`).

To resolve the DescTools problem I would add the two packages to the installed requirements. However, it could also be worthwhile to deactivate the quiet installation of the r packages, as this results in silent errors. Does this serve a purpose?

I will try to create a PR for this in the coming days.

**Comment by donsizemore** [comment]
Looks like there's some duplication between
https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/develop/tasks/rserve.yml#L35
and
https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/develop/tasks/rserve.yml#L42
but you may just want to add those two packages to line 42, and do away with the "distribution" check?

I'm personally not sure why `quiet=TRUE` - the task seems to generate plenty of output with that in place?

**Comment by HenningTimm** [comment]
Ansible continuing after the installation of DescTools (or any package) fails does not seem to be the fault of `quiet=TRUE`. It seems that [Rscript does not pass on that return code.](https://stackoverflow.com/questions/60391125/rscript-install-packages-how-to-make-it-fail-with-an-error-code)

For some context: The quiet option was introduced in https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/issues/1 to reduce the verbose output generated by Rscript when installing packages.

An alternative to the current RScript solution would be to use the [CRAN module](https://galaxy.ansible.com/yutannihilation/module-cran) from Ansible Galaxy. On the other hand, that one is 6 years old and I am not sure if it supports multicore compilation. Another option would be to use the [`install_packages_or_die.R` script](https://stackoverflow.com/questions/26244530/how-do-i-make-install-packages-return-an-error-if-an-r-package-cannot-be-install). Finally, we could try to use [conda](https://github.com/evandam/evandam.conda).

I will do some more research. I am confused that there does not seem to be a better/ more solid way to install R packages with ansible.

**Comment by HenningTimm** [comment]
I was not able to reliably the cran module to run. Using one line from the `install_packages_or_die` script did the trick however. Introducing conda would probably make everything more difficult so adding a line that makes the task actually fail seems like the best way to me.
