### ISSUE TITLE
5.13 version bump

### ISSUE THREAD

**Issue by pdurbin** [GlobalDataverseCommunityConsortium/dataverse-ansible#267]
I just created a PR to bump the version to 5.13: https://github.com/IQSS/dataverse/pull/9373

Over at https://guides.dataverse.org/en/5.12.1/developers/making-releases.html we say:

"Please note that you will need to bump the version in [jenkins.yml](https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/develop/tests/group_vars/jenkins.yml) in dataverse-ansible to get the tests to pass. Consider doing this before making the pull request. Alternatively, you can bump jenkins.yml after making the pull request and re-run the Jenkins job to make sure tests pass."

So we need some version bumping in the new future, please. 🙏 

It looks like last time we bumped for testing: fa1885a

Then for the release later: 3424aac

**Comment by pdurbin** [comment]
https://github.com/IQSS/dataverse/pull/9373 has been merged so @donsizemore if you're able to do the bumping, I'd appreciate it!

**Comment by donsizemore** [comment]
@pdurbin I was bay-ud and already did it in https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/commit/a9562d6e4ed938f85584047bf18a04d756ec1638
