### ISSUE TITLE
Fails on Debian 11 with umask 077

### ISSUE THREAD

**Issue by maximilian-tech** [GlobalDataverseCommunityConsortium/dataverse-ansible#269]
`ansible-playbook` fails on Debian 11.

```
$ git clone https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible.git dataverse
$ sudo ansible-playbook --connection=local -v -i dataverse/inventory dataverse/dataverse.pb -e "@dataverse/defaults/main.yml"
```
leads to 
```
TASK [dataverse : reload systemd, enable rserve, start] ********************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to start service rserve: Job for rserve.service failed because the control process exited with error code.\nSee \"systemctl status rserve.service\" and \"journalctl -xe\" for details.\n"}
```

systemctl
```
$ systemctl status rserve.service
● rserve.service - Rserve
     Loaded: loaded (/lib/systemd/system/rserve.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-02-17 10:29:22 CET; 3min 16s ago
    Process: 16136 ExecStartPre=/usr/bin/mkdir -p /var/run/rserve (code=exited, status=0/SUCCESS)
    Process: 16137 ExecStartPre=/usr/bin/chown -R rserve:rserve /var/run/rserve (code=exited, status=0/SUCCESS)
    Process: 16138 ExecStart=/usr/bin/R CMD Rserve --quiet --vanilla --RS-conf /etc/Rserv.conf --RS-pidfile /var/run/rserve/rserve.pid (code=exited, status=127)
        CPU: 6ms

```

Any ideas?

**Comment by maximilian-tech** [comment]
`Rserve` is not available:

```
$ /usr/bin/R CMD Rserve
/usr/lib/R/bin/Rcmd: 64: exec: Rserve: not found

$ /usr/bin/R --help

Usage: R [options] [< infile] [> outfile]
   or: R CMD command [arguments]
...
Commands:
  BATCH			Run R in batch mode
  COMPILE		Compile files for use with R
  SHLIB			Build shared library for dynamic loading
  INSTALL		Install add-on packages
  REMOVE		Remove add-on packages
  build			Build add-on packages
  check			Check add-on packages
  LINK			Front-end for creating executable programs
  Rprof			Post-process R profiling files
  Rdconv		Convert Rd format to various other formats
  Rd2pdf		Convert Rd format to PDF
  Rd2txt		Convert Rd format to pretty text
  Stangle		Extract S/R code from Sweave documentation
  Sweave		Process Sweave documentation
  Rdiff			Diff R output ignoring headers etc
  config		Obtain configuration information about R
  javareconf		Update the Java configuration variables
  rtags                 Create Emacs-style tag files from C, R, and Rd files
...


$ /usr/bin/R --version
R version 4.0.4 (2021-02-15) -- "Lost Library Book"
```
Rserve is not in the list of commands. It does however exist on the system:
```
$ locate Rserve
/usr/lib/R/bin/Rserve
/usr/lib/R/bin/Rserve.dbg
/usr/local/lib/R/site-library/Rserve
/usr/local/lib/R/site-library/Rserve/DESCRIPTION
/usr/local/lib/R/site-library/Rserve/INDEX
/usr/local/lib/R/site-library/Rserve/LICENSE
/usr/local/lib/R/site-library/Rserve/Meta
/usr/local/lib/R/site-library/Rserve/NAMESPACE
/usr/local/lib/R/site-library/Rserve/NEWS
/usr/local/lib/R/site-library/Rserve/R
/usr/local/lib/R/site-library/Rserve/help
/usr/local/lib/R/site-library/Rserve/html
/usr/local/lib/R/site-library/Rserve/java
/usr/local/lib/R/site-library/Rserve/libs
/usr/local/lib/R/site-library/Rserve/Meta/Rd.rds
/usr/local/lib/R/site-library/Rserve/Meta/features.rds
/usr/local/lib/R/site-library/Rserve/Meta/hsearch.rds
/usr/local/lib/R/site-library/Rserve/Meta/links.rds
/usr/local/lib/R/site-library/Rserve/Meta/nsInfo.rds
/usr/local/lib/R/site-library/Rserve/Meta/package.rds
/usr/local/lib/R/site-library/Rserve/R/Rserve
/usr/local/lib/R/site-library/Rserve/R/Rserve.rdb
/usr/local/lib/R/site-library/Rserve/R/Rserve.rdx
/usr/local/lib/R/site-library/Rserve/help/AnIndex
/usr/local/lib/R/site-library/Rserve/help/Rserve.rdb
/usr/local/lib/R/site-library/Rserve/help/Rserve.rdx
/usr/local/lib/R/site-library/Rserve/help/aliases.rds
/usr/local/lib/R/site-library/Rserve/help/paths.rds
/usr/local/lib/R/site-library/Rserve/html/00Index.html
/usr/local/lib/R/site-library/Rserve/html/R.css
/usr/local/lib/R/site-library/Rserve/java/REngine.jar
/usr/local/lib/R/site-library/Rserve/java/Rserve.jar
/usr/local/lib/R/site-library/Rserve/libs/Rserve
/usr/local/lib/R/site-library/Rserve/libs/Rserve.dbg
/usr/local/lib/R/site-library/Rserve/libs/Rserve.so
/usr/local/lib/R/site-library/Rserve/libs/forward
```

Any help is appreciated!

**Comment by donsizemore** [comment]
What happens when you run `/usr/bin/R CMD Rserve --quiet --vanilla --RS-conf /etc/Rserv.conf --RS-pidfile /var/run/rserve/rserve.pid` as the `rserve` user?

**Comment by maximilian-tech** [comment]
Thanks for the quick reply!

Unfortunately no success:

```
$ su -c  "id && /usr/bin/R CMD Rserve --quiet --vanilla --RS-conf /etc/Rserv.conf --RS-pidfile /var/run/rserve/rserve.pid" rserve
uid=1004(rserve) gid=1004(rserve) groups=1004(rserve)
/usr/lib/R/bin/Rcmd: 64: exec: Rserve: not found
```

I had to reset the password of rserve using `sudo passwd -d rserve`

**Comment by donsizemore** [comment]
Do you happen to have the output of the Rserve task, from your run?

The only OS-specific clause I see is https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/develop/tasks/rserve.yml#L41

If Ansible wasn't able to install the Rserve R module, the run should've failed.

**Comment by maximilian-tech** [comment]
The complete log is appended. 

There are some warnings, strings seem to be clobbered.

```
...
install.packages('Rserve', repos=c('https://cloud.r-project.org/', Ncpus='4', quiet=TRUE));
...
Warning: unable to access index for repository 4/src/contrib:
  cannot open URL '4/src/contrib/PACKAGES'
Warning: unable to access index for repository TRUE/src/contrib:
  cannot open URL 'TRUE/src/contrib/PACKAGES'
```


```
$ ansible-playbook --version 
ansible-playbook 2.10.8
```

[log.install_dataverse.txt](https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/files/10769900/log.install_dataverse.txt)

**Comment by donsizemore** [comment]
It looks like your R library prefix is messed up, though I'm not sure how or why. Dataverse-Ansible doesn't specify a library prefix, and it looks like Debian defaults to /usr/lib rather than /usr/local/lib. Was this a clean install, or did you have any existing R configuration on the host?

**Comment by maximilian-tech** [comment]
>  R library prefix is messed up

I created a [PR](https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/pull/270).

The og. problem is, that Rserve is only root accessible
```
$ ll /usr/lib/R/bin/
....
-rwxr-xr-x 1 root root  14552 Feb 15  2021 Rscript
-rwx------ 1 root root 592968 Feb 17 22:48 Rserve
-rwx------ 1 root root 688016 Feb 17 22:48 Rserve.dbg
....
```

**Comment by maximilian-tech** [comment]
This error can be fixed by adding 
```
ExecStartPre=/usr/bin/chmod 755 /usr/lib/R/bin/Rserve /usr/lib/R/bin/Rserve.dbg
```
to `templates/rserve.service.j2`

There should probably be code to detect where `Rserve` actually is, or better, make sure `Rserve` is 755 from the beginning.

**Comment by maximilian-tech** [comment]
New error when starting `solr.service`.
```
$ systemctl status solr.service
     solr.service - Apache Solr
     Loaded: loaded (/etc/systemd/system/solr.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-02-17 23:14:49 CET; 32s ago
    Process: 25002 ExecStart=/usr/local/solr/bin/solr start -j jetty.host=127.0.0.1 (code=exited, status=1/FAILURE)
```
Missing access rights to Solr home
```
solr@dataverse-test-debian:$ /usr/local/solr/bin/solr start -j jetty.host=127.0.0.1

Solr home directory /usr/local/solr/server/solr not found!
```
Again, access rights are 700 for root
```
root@dataverse-test-debian:$ ll /usr/local/solr/server/
...
drwx------ 1 root root     26 Feb 17 23:14 scripts
drwx------ 1 root root    128 Feb 17 23:14 solr
drwx------ 1 root root     12 Feb 17 23:14 solr-webapp
...
```

**Comment by donsizemore** [comment]
Are you using a CISecurity-hardened image or some such? I tested the role with Debian 11 back when it was released, and didn't run into any of this.

**Comment by donsizemore** [comment]
> > R library prefix is messed up
> 
> I created a [PR](https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/pull/270).
> 
> The og. problem is, that Rserve is only root accessible
> 
> ```
> $ ll /usr/lib/R/bin/
> ....
> -rwxr-xr-x 1 root root  14552 Feb 15  2021 Rscript
> -rwx------ 1 root root 592968 Feb 17 22:48 Rserve
> -rwx------ 1 root root 688016 Feb 17 22:48 Rserve.dbg
> ....
> ```

This sounds like a packaging problem in the distribution, or perhaps an intentional security measure.

**Comment by donsizemore** [comment]
> New error when starting `solr.service`.
> 
> ```
> $ systemctl status solr.service
>      solr.service - Apache Solr
>      Loaded: loaded (/etc/systemd/system/solr.service; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Fri 2023-02-17 23:14:49 CET; 32s ago
>     Process: 25002 ExecStart=/usr/local/solr/bin/solr start -j jetty.host=127.0.0.1 (code=exited, status=1/FAILURE)
> ```
> 
> Missing access rights to Solr home
> 
> ```
> solr@dataverse-test-debian:$ /usr/local/solr/bin/solr start -j jetty.host=127.0.0.1
> 
> Solr home directory /usr/local/solr/server/solr not found!
> ```
> 
> Again, access rights are 700 for root
> 
> ```
> root@dataverse-test-debian:$ ll /usr/local/solr/server/
> ...
> drwx------ 1 root root     26 Feb 17 23:14 scripts
> drwx------ 1 root root    128 Feb 17 23:14 solr
> drwx------ 1 root root     12 Feb 17 23:14 solr-webapp
> ...
> ```

by default Ansible installs Solr as a `solr` service account - you don't want to run Solr as root. Ansible doesn't touch the system default umask but does specify the mode on Solr root: https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/develop/tasks/solr.yml#L47 so ... what's your system's default umask, and has the OS been hardened in any way?

**Comment by maximilian-tech** [comment]
> what's your system's default umask

```
$ umask
0077
```
I didn't know about umask! This seems to be the issue. Is it possible (in theory) to make the ansible playbook "umask 077" ready? 

> and has the OS been hardened in any way? 

I am waiting for a response from the university IT team!

**Comment by donsizemore** [comment]
@maximilian-tech Ansible can check for this, and correct for it, yes, but... you don't want to run Solr (or Payara, or Rserve) as root, and in the case of Solr I suspect if you correct the ownership issue the systemd problem will go away. If your admins want to preserve the umask for security, /usr/lib/R could pretty easily be chowned to the rserve user, though this would arguably be worse for security.

**Comment by maximilian-tech** [comment]
> and has the OS been hardened in any way?

Got response from the IT department, the OS is not hardened.
Setting `umask 022` and executing the playbook does work.

Closing this issue as a failing installation with `umask 077` is expected. 

Thanks @donsizemore for quick response and the tip with the wrong `umask`!
