### ISSUE TITLE
adjust language pack locales

### ISSUE THREAD

**Issue by donsizemore** [GlobalDataverseCommunityConsortium/dataverse-ansible#274]
Current language task, when enabled, dies:

```
cp -R de-DE*/*.properties
cp: cannot stat 'de-DE*/*.properties': No such file or directory
```

vagrant.yml sez:
```
locale: en
locale: de-DE
```

but `/tmp/dataverse_language_packs` contains:
```
en_US/
de_DE/
```

Probably just need to adjust group_var entries to match.

**Comment by donsizemore** [comment]
@pallinger before I create a branch and submit a PR, should ^^ be all that needs to happen? Does this seem like a sound solution to you?

**Comment by pallinger** [comment]
It seems ok, you can change the defaults. I use an older language-pack that contains such language directories, but the default should be what is in gdcc repo.
