### ISSUE TITLE
support Debian 12

### ISSUE THREAD

**Issue by donsizemore** [GlobalDataverseCommunityConsortium/dataverse-ansible#297]
if we don't already. maybe we already do. test.

**Comment by donsizemore** [comment]
looks like openjdk-11 isn't readily available for Debian 12: https://www.reddit.com/r/debian/comments/14fjgus/need_help_installing_openjdk11_on_debian_12/

**Comment by pallinger** [comment]
I started to work on it. There needs to be a change in `install.py` to accept java 17 (I will send a pull request), and also there is some postgres authorization error that I do not know the cause of yet.

**Comment by donsizemore** [comment]
I see what you mean in install.py - if Deb12 ships with PG15 the cause may be https://github.com/IQSS/dataverse/issues/9717
I stopped as I wasn't sure whether to minimally grant CREATE, or ALL, or some subset of permissions.

Note that Dataverse itself won't fully support Java 17 until major version 6, or shortly thereafter.
