### ISSUE TITLE
Support Payara 6 when rsyncing files

### ISSUE THREAD

**Issue by pdurbin** [GlobalDataverseCommunityConsortium/dataverse-ansible#306]
https://jenkins.dataverse.org/job/IQSS-Dataverse-Payara6/52/consoleFull has the following error:

"rsync: change_dir "/usr/local/payara5/glassfish/domains/domain1/logs" failed: No such file or directory (2)"

It looks like https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/develop/ec2/ec2-create-instance.sh has payara5 hard-coded in a couple places:

`rsync -av -e "ssh -i $PEM_FILE" --ignore-missing-args $AWS_USER@$PUBLIC_DNS:/usr/local/payara5/glassfish/domains/domain1/logs/server* $LOCAL_LOG_PATH/`

`rsync -av -e "ssh -i $PEM_FILE" --ignore-missing-args $AWS_USER@$PUBLIC_DNS:/usr/local/payara5/glassfish/domains/domain1/logs/server.log* $LOCAL_LOG_PATH/`

Maybe this should be a glob? `paraya*`? Whatever makes sense.

**Comment by donsizemore** [comment]
@pdurbin since this isn't templated by Ansible, I'll probably just bump it in a payara6 branch and merge with develop when IQSS makes the switch? my plate is full today, so I'll give it more than a band-aid later.
