### ISSUE TITLE
DescTools is not available for this version of R

### ISSUE THREAD

**Issue by RoHei** [GlobalDataverseCommunityConsortium/dataverse-ansible#348]
Hi, when running your nice and estensive playbooks, I unfortunately get the following error during the R-Package installation:
`DescTools is not available for this version of R. DescTools version 0.99.54 is in the repositories but depends on R (>=4.2.0). `

No R installation was previously existing before running the playbooks
It is now given as: `R version 4.1.2 (2021-11-01)`

So either R should be updated or a compatible version of `DescTools` is required.

**Comment by donsizemore** [comment]
Hello, what operating system were you using? The Ansible role makes no mention of R version: https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/develop/tasks/rserve.yml#L34

Rocky Linux 9 currently provides R-core 4.3.3, so you should be fine on any operating system which bundles a new-enough R installation.

Note that R is optional and not-at-all required for Dataverse installation, so you may simply set `rserve.enabled: false` in your group_vars file.

**Comment by RoHei** [comment]
Hi, thanks for the fast reply. My Operating System is: Ubuntu 22.04.1 LTS and it was a fresh installation.

I deactivated the conflicting package in the playbooks - but anyways this maybe should fixed, given that I used a standard OS at all. As far is I know, R was not installed previously so it was installed by Ansible now.

**Comment by donsizemore** [comment]
Hello, I'm seeing R-4.3.3 packaged for Ubuntu 20.04.6 LTS, so I'm not certain how you're getting 4.1.2. The Ansible role specifies no R-core version, it simply installs the latest version available from the operating system. If you think R should be installed in some other way, you're most welcome to submit a pull request?

**Comment by RoHei** [comment]
Hm thats interesting. Then it is apparently an issue on my side. Maybe the Ubuntu package repository was not up to date. 
Thanks anyways!
