### ISSUE TITLE
enable dataverse-previewers task failing with non-zero return code

### ISSUE THREAD

**Issue by pdurbin** [GlobalDataverseCommunityConsortium/dataverse-ansible#358]
I'm on 2d7f797 and tried running the create script with the Rocky 9 image like this:

`./ec2-create-instance.sh -i ami-06b7b440778b965d8`

TASK [dataverse : enable dataverse-previewers] *********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/root/dataverse-previewers.sh", "delta": "0:00:00.374620", "end": "2024-05-28 19:45:57.237191", "msg": "non-zero return code", "rc": 1, "start": "2024-05-28 19:45:56.862571", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100    25  100    25    0     0    238      0 --:--:-- --:--:-- --:--:--   238", "stderr_lines": ["  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0", "100    25  100    25    0     0    238      0 --:--:-- --:--:-- --:--:--   238"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=184  changed=101  unreachable=0    failed=1    skipped=365  rescued=0    ignored=0 

Here's the full output: [install-fail-2d7f797-el9.txt](https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/files/15475509/install-fail-2d7f797-el9.txt)

@pallinger can you please take a look? The error seems to be related to this recent PR:

- #356

**Comment by donsizemore** [comment]
@pallinger are you able to take a look at this?
