### ISSUE TITLE
Extra packages needed for upgrade instructions for v6.5

### ISSUE THREAD

**Issue by ofahimIQSS** [GlobalDataverseCommunityConsortium/dataverse-ansible#383]
[rocky@ip-172-31-48-54 tmp]$ sudo ./update-fields.sh /usr/local/server/solr/collection1/conf/schema.xml
ERROR: Please ensure ed, bc, sed + awk are installed

I had to also install wget earlier.

**Comment by pdurbin** [comment]
Here's where the error gets triggered:

https://github.com/IQSS/dataverse/blob/v6.4/conf/solr/update-fields.sh#L70-L74

And earlier in the release notes we need wget.

So, in practice, these are the three packages we need: wget bc ed.

That is to say, sed and awk are already installed.

**Comment by pdurbin** [comment]
@donsizemore thanks for fixing! ❤️
