### ISSUE TITLE
failure during "create localstack bucket for testing" step

### ISSUE THREAD

**Issue by pdurbin** [GlobalDataverseCommunityConsortium/dataverse-ansible#387]
Lately we've seen some errors like this:

`TASK [dataverse : create localstack bucket for testing] ************************`
`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "aws --endpoint=http\\://localhost\\:4566 s3 mb s3://mybucket", "
delta": "0:00:01.822646", "end": "2024-12-11 19:59:53.755025", "msg": "non-zero return code", "rc": 1, "start": "2024-12-
11 19:59:51.932379", "stderr": "make_bucket failed: s3://mybucket Connection was closed before we received a valid respon
se from endpoint URL: \"http://localhost:4566/mybucket\".", "stderr_lines": ["make_bucket failed: s3://mybucket Connectio
n was closed before we received a valid response from endpoint URL: \"http://localhost:4566/mybucket\"."], "stdout": "", 
"stdout_lines": []}`

I'm not sure why. That was from https://jenkins.dataverse.org/job/IQSS-dataverse-develop/1945/console today.

In a [Slack thread](https://iqss.slack.com/archives/C03R1E7T4KA/p1733947347007719) we've mentioned a couple other recent occurrences:

- https://jenkins.dataverse.org/job/IQSS-dataverse-develop/1920/console
- https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-11091/2/console

At the very least we should keep an eye on it.

**Comment by donsizemore** [comment]
These appear to be intermittent, and I'm afraid that I haven't been able to reproduce them during the past two manual runs of the Jenkins workflow. I may need a live specimen to debug further.

**Comment by qqmyers** [comment]
This seems to have a bucket issue: https://jenkins.dataverse.org/blue/organizations/jenkins/IQSS-Dataverse-Develop-PR/detail/PR-10856/30/pipeline/ along with this one: https://jenkins.dataverse.org/blue/organizations/jenkins/IQSS-Dataverse-Develop-PR/detail/PR-7636/26/pipeline

**Comment by qqmyers** [comment]
Would it make sense to try adding `--cli-connect-timeout 120` to that call? I think [the default is 60 seconds](https://docs.aws.amazon.com/cli/latest/reference/).
