### ISSUE TITLE
Potential wrong path on default config

### ISSUE THREAD

**Issue by espenfl** [GlobalDataverseCommunityConsortium/dataverse-ansible#73]
Thanks for developing this excellent Ansible role.

Tried commit `4e95bb5c173422fc15785f0934c3579d6e10faa4` on CentOS 8 and ran into an issue. The `--config-file=default.config`, here https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/4e95bb5c173422fc15785f0934c3579d6e10faa4/tasks/dataverse-install.yml#L114 should be `--config_file=/tmp/dvinstall/default.config`. At least to make it fly with the defaults.

**Comment by donsizemore** [comment]
There's a chdir in there: https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/blob/4e95bb5c173422fc15785f0934c3579d6e10faa4/tasks/dataverse-install.yml#L118

Did your run not find default.config? If not, what Ansible version/platform?

**Comment by espenfl** [comment]
@donsizemore Thanks. No, it did not pick it up. Strange, will do a bit more testing to see if I can reproduce. Was an instance on Azure running CentOS 8 and Ansible 2.10.x I believe.

**Comment by espenfl** [comment]
Closing this as this was a mistake on my part. Sorry for the confusion.
