### ISSUE TITLE
Certbot options not setting certificate file and key for apache configs

### ISSUE THREAD

**Issue by espenfl** [GlobalDataverseCommunityConsortium/dataverse-ansible#74]
When enabling `apache.ssl.enabled`, `letsencrypt.enabled` (also setting `payara.siteurl` to the correct domain) it is my impression by looking at the variables that Certbot is executed (which it also does correctly). Certificates are valid and stored in the usual places so that works. But then the Apache configs are not updated. Is this right, or am I missing some details here? Thanks.

**Comment by donsizemore** [comment]
@espenfl In general Certbot updates the Apache configs for you but I haven't done much work or testing on the SSL bits of this role. Are you not getting the desired results? Certbot may need a flag to tell it which .conf file to update.

**Comment by espenfl** [comment]
@donsizemore Yes, I think what we need is to run it with the `--apache`, which also requires the plugin (`python3-certbot-apache` on CentOS 8 I believe). I tried to just do `sudo certbot --apache` after the playbook stopped when trying a restart after running Certbot (also verified that the apache logs complained about SSL certs) followed by a manual restart, which worked.

**Comment by espenfl** [comment]
Or we do it manually. Now it is executed with `certonly` which only fetches the certs. I guess this is fine, but then we need to update the configs manually I believe.

**Comment by donsizemore** [comment]
@espenfl perfect. Most of my testing is done in either Vagrant or EC2, neither supported by CertBot. Would you like to make a pull request?

**Comment by espenfl** [comment]
Sure, happy to do this.
