### ISSUE TITLE
Payara fails to start due to complaints about occupied admin port

### ISSUE THREAD

**Issue by espenfl** [GlobalDataverseCommunityConsortium/dataverse-ansible#77]
When the installer wants to start payara it complains with the message `There is a process already using the admin port 4848`. I do not really understand why this is happening and why the fix of injecting `127.0.0.1 yourdomain` into `/etc/hosts` makes this issue go away. Granted, there are some operations that do not work on `yourdomain`, like `ping` etc. it is still a perfectly valid address that resolved with e.g. `dig`. Anyone experienced this before?

**Comment by donsizemore** [comment]
I've honestly never seen the role complain about this before. Can you send me the console output from payara to installer?
