### ISSUE TITLE
Timeout to start payara service

### ISSUE THREAD

**Issue by dmelichar** [GlobalDataverseCommunityConsortium/dataverse-ansible#85]
Hello.

I'm using the scripts to install the entire stack on a local Vagrant machine . I noticed that the domain throws a HTTP 503 when the machine reboots. After some investigation I found that the created `systemd` service times out. 

``` bash
[root@dataverse-centos8 ~]# systemctl status payara
  payara.service - Payara Server
   Loaded: loaded (/usr/lib/systemd/system/payara.service; enabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Fri 2020-11-13 16:16:54 UTC; 2min 45s ago
  Process: 844 ExecStart=/usr/bin/java -jar /usr/local/payara5/glassfish/lib/client/appserver-cli.jar start-domain (code=exited, status=143)

Nov 13 16:12:52 dataverse-centos8 systemd[1]: Starting Payara Server...
Nov 13 16:15:53 dataverse-centos8 systemd[1]: payara.service: Start operation timed out. Terminating.
Nov 13 16:15:54 dataverse-centos8 systemd[1]: payara.service: Control process exited, code=exited status=143
Nov 13 16:16:54 dataverse-centos8 systemd[1]: payara.service: Failed with result 'timeout'.
Nov 13 16:16:54 dataverse-centos8 systemd[1]: Failed to start Payara Server.
```

I manually changed `TimeoutStartSec` to 300 seconds in `/usr/lib/systemd/system/payara.service`. I recommend increasing the default parameter `payara.launch_timeout` to automatically do this when installing and avoid the manual step.

**Comment by donsizemore** [comment]
@dmelichar that's fine, but how many cores are you giving the vagrant VM? If Payara is taking more than 3 minutes to launch, something else is wrong.

**Comment by dmelichar** [comment]
Oh that makes sense. I'm only using 1 core. 

Thanks!
